apiVersion: nfd.kubernetes.io/v1alpha1
kind: NodeFeatureDiscovery
metadata:
  name: nfd-master-server
  namespace: REPLACE_NAMESPACE
spec:
  namespace: node-feature-discovery-operator
  image: k8s.gcr.io/nfd/node-feature-discovery:v0.6.0
