apiVersion: nfd.kubernetes.io/v1alpha1
kind: NodeFeatureDiscovery
metadata:
  name: nfd-master-server 
  namespace: REPLACE_NAMESPACE
spec:
  namespace: node-feature-discovery-operator
  image: quay.io/kubernetes_incubator/node-feature-discovery:v0.5.0
