kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node-feature-discovery-operator
subjects:
- kind: ServiceAccount
  name: node-feature-discovery-operator
  namespace: REPLACE_NAMESPACE 
roleRef:
  kind: ClusterRole
  name: node-feature-discovery-operator
  apiGroup: rbac.authorization.k8s.io
